image:
  tag: latest
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: kanastra-app-dev.duckdns.org
      paths:
        - path: /
          pathType: ImplementationSpecific
#  tls:
#    - hosts:
#        - kanastra-app-dev.duckdns.org
#      secretName: kanastra-app-dev-secret