image:
  tag: latest
ingress:
  hosts:
    - host: kanastra-app.duckdns.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - kanastra-app.duckdns.org
      secretName: kanastra-app-prd-secret